---
version: '3.8'
services:

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./ssl-cert-snakeoil.key:/certs/server.key:ro
      - ./ssl-cert-snakeoil.pem:/certs/server.cer:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SERVER: localhost
      SERVER_KEY: /certs/server.key
      SERVER_CERT: /certs/server.cer
    depends_on:
      - taskusama

  taskusama:
    image: fakelassian/taskusama:latest
    container_name: taskusama
    restart: unless-stopped
    environment:
      PORT: "8080"
      DATABASE_URL: "postgres://taskusama:taskusama@postgresql_taskusama:5432/taskusama?sslmode=disable"
      MIGRATIONS_PATH: "/migrations"
    volumes:
      - ./migrations:/migrations:ro
      # - ./.env:/.env:ro
    # depends_on:
    #   postgresql_taskusama:
    #     condition: service_healthy
    expose:
      - "8080"

  postgresql_taskusama:
    image: postgres:18.1-bookworm
    container_name: postgresql_taskusama
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskusama
      POSTGRES_USER: taskusama
      POSTGRES_PASSWORD: taskusama
    volumes:
      - taskusama_db:/var/lib/postgresql/data
      - ./ssl-cert-snakeoil.key:/certs/server.key:ro
      - ./ssl-cert-snakeoil.pem:/certs/server.cer:ro
    command:
      - postgres
      - -c
      - ssl=on
      - -c
      - ssl_cert_file=/certs/server.cer
      - -c
      - ssl_key_file=/certs/server.key
      - -c
      - ssl_min_protocol_version=TLSv1.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
    # Donâ€™t publish 5432 unless you need host access
    expose:
      - "5432"

volumes:
  taskusama_db:
  caddy_data:
  caddy_config:

