---
version: '3.8'
services:

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/html:/usr/share/caddy
      - $PWD/ssl-cert-snakeoil.key:/certs/server.key:ro
      - $PWD/ssl-cert-snakeoil.pem:/certs/server.cer:ro
    environment:
      SERVER: localhost
      SERVER_KEY: '/certs/server.key'
      SERVER_CERT: '/certs/server.cer'

  taskusama:
    image: fakelassian/taskusama:latest
    container_name: taskusama
    restart: unless-stopped
    ports:
      - 8080:8080

  postgresql_taskusama:
    image: postgres:18.1-bookworm
    container_name: postgresql_taskusama
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - /var/fakelassian-db:/var/lib/postgresql/18/docker
      - $PWD/ssl-cert-snakeoil.key:/certs/server.key:ro
      - $PWD/ssl-cert-snakeoil.pem:/certs/server.cer:ro
    environment:
      SERVER_KEY: '/certs/server.key'
      SERVER_CERT: '/certs/server.cer'
    command:
      - postgres
      - -c
      - ssl=on
      - -c
      - ssl_cert_file=/certs/server.cer
      - -c
      - ssl_key_file=/certs/server.key
      - -c
      - ssl_min_protocol_version=TLSv1.2
